"""add agent runs and steps

Revision ID: 4abfa7cd5dd7
Revises: c9185f28bfa1
Create Date: 2026-07-16 20:01:36.866206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abfa7cd5dd7'
down_revision: Union[str, Sequence[str], None] = 'c9185f28bfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('FINANCIAL_ANALYST', 'RISK_ANALYST', 'COMPLIANCE_REVIEWER', 'DOCUMENT_RESEARCHER', 'EXECUTIVE_SUMMARY', name='agent_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agent_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('execution_metadata', sa.JSON(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True),
    sa.Column('generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_type'), 'agent_runs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_by'), 'agent_runs', ['created_by'], unique=False)
    op.create_index(op.f('ix_agent_runs_knowledge_base_id'), 'agent_runs', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('PLANNING', 'RETRIEVAL', 'ANALYSIS', 'GENERATION', 'CITATION', 'VALIDATION', name='agent_step_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='agent_step_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=150), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=False),
    sa.Column('tool_output', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_steps_agent_run_id'), 'agent_run_steps', ['agent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_run_steps_agent_run_id'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_knowledge_base_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_by'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_type'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
